-- Create a table to track SRS progress for flashcards
create table if not exists public.flashcard_reviews (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  question_id bigint references public.questions not null,
  next_review_at timestamptz not null,
  interval_days float4 not null default 1.0, -- Current interval in days
  ease_factor float4 not null default 2.5, -- SM-2 ease factor
  repetitions integer not null default 0, -- Number of consecutive successful recalls
  last_reviewed_at timestamptz not null default now(),
  created_at timestamptz default now(),
  
  -- Ensure one review record per user per question
  unique(user_id, question_id)
);

-- RLS Policies
alter table public.flashcard_reviews enable row level security;

create policy "Users can view their own flashcard reviews"
  on public.flashcard_reviews for select
  using (auth.uid() = user_id);

create policy "Users can insert their own flashcard reviews"
  on public.flashcard_reviews for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own flashcard reviews"
  on public.flashcard_reviews for update
  using (auth.uid() = user_id);
