-- Create referral_codes table
CREATE TABLE IF NOT EXISTS public.referral_codes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text UNIQUE NOT NULL,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL
);

-- Create referrals table
CREATE TABLE IF NOT EXISTS public.referrals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    referrer_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    referee_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    referral_code text NOT NULL,
    used_for_unlock boolean DEFAULT false NOT NULL,
    unlocked_bank_id bigint REFERENCES public.question_banks(id) ON DELETE SET NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    UNIQUE(referee_id) -- A user can only be referred once
);

-- Create user_bank_unlocks table
CREATE TABLE IF NOT EXISTS public.user_bank_unlocks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    bank_id bigint REFERENCES public.question_banks(id) ON DELETE CASCADE NOT NULL,
    unlock_type text NOT NULL CHECK (unlock_type IN ('referral', 'purchase', 'admin')),
    referral_id bigint REFERENCES public.referrals(id) ON DELETE SET NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    UNIQUE(user_id, bank_id)
);

-- Add unlock_type to question_banks
ALTER TABLE public.question_banks 
ADD COLUMN IF NOT EXISTS unlock_type text DEFAULT 'free' 
CHECK (unlock_type IN ('free', 'premium', 'referral'));

-- Add indexes
CREATE INDEX IF NOT EXISTS idx_referral_codes_user_id ON public.referral_codes(user_id);
CREATE INDEX IF NOT EXISTS idx_referral_codes_code ON public.referral_codes(code);
CREATE INDEX IF NOT EXISTS idx_referrals_referrer_id ON public.referrals(referrer_id);
CREATE INDEX IF NOT EXISTS idx_referrals_referee_id ON public.referrals(referee_id);
CREATE INDEX IF NOT EXISTS idx_user_bank_unlocks_user_id ON public.user_bank_unlocks(user_id);
CREATE INDEX IF NOT EXISTS idx_user_bank_unlocks_bank_id ON public.user_bank_unlocks(bank_id);

-- Enable RLS
ALTER TABLE public.referral_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.referrals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_bank_unlocks ENABLE ROW LEVEL SECURITY;

-- Policies for referral_codes
CREATE POLICY "Users can view their own referral code" 
ON public.referral_codes FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Anyone can look up referral codes" 
ON public.referral_codes FOR SELECT 
USING (true); -- Needed for verifying codes during signup

CREATE POLICY "Users can create their own referral code" 
ON public.referral_codes FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- Policies for referrals
CREATE POLICY "Users can view referrals they sent or received" 
ON public.referrals FOR SELECT 
USING (auth.uid() = referrer_id OR auth.uid() = referee_id);

CREATE POLICY "System can insert referrals" 
ON public.referrals FOR INSERT 
WITH CHECK (true); -- Usually handled by server actions, but keeping flexible

-- Policies for user_bank_unlocks
CREATE POLICY "Users can view their own unlocks" 
ON public.user_bank_unlocks FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "System can manage unlocks" 
ON public.user_bank_unlocks FOR ALL 
USING (true);

-- Admin policies (assuming admin checks are done in application logic or via specific roles)
-- For simplicity, we'll allow authenticated users to view but restricted operations will be backend-only or via secure functions

