-- Migration: Add user collections and tracking for question banks and exams
-- Created: 2026-01-22

-- ============================================
-- 1. Create user_question_bank_collections table
-- ============================================
CREATE TABLE IF NOT EXISTS "public"."user_question_bank_collections" (
    "id" bigint NOT NULL,
    "user_id" uuid NOT NULL,
    "bank_id" bigint NOT NULL,
    "added_at" timestamp with time zone DEFAULT now() NOT NULL,
    "completion_count" integer DEFAULT 0 NOT NULL,
    "last_completed_at" timestamp with time zone
);

ALTER TABLE "public"."user_question_bank_collections" OWNER TO "postgres";

ALTER TABLE "public"."user_question_bank_collections" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_question_bank_collections_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Primary key
ALTER TABLE ONLY "public"."user_question_bank_collections"
    ADD CONSTRAINT "user_question_bank_collections_pkey" PRIMARY KEY ("id");

-- Unique constraint
ALTER TABLE ONLY "public"."user_question_bank_collections"
    ADD CONSTRAINT "user_question_bank_collections_user_bank_unique" UNIQUE ("user_id", "bank_id");

-- Foreign keys
ALTER TABLE ONLY "public"."user_question_bank_collections"
    ADD CONSTRAINT "user_question_bank_collections_user_id_fkey" 
    FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."user_question_bank_collections"
    ADD CONSTRAINT "user_question_bank_collections_bank_id_fkey" 
    FOREIGN KEY ("bank_id") REFERENCES "public"."question_banks"("id") ON DELETE CASCADE;

-- Enable RLS
ALTER TABLE "public"."user_question_bank_collections" ENABLE ROW LEVEL SECURITY;

-- RLS Policy
CREATE POLICY "Users can manage their own question bank collections" 
    ON "public"."user_question_bank_collections" 
    USING (auth.uid() = user_id) 
    WITH CHECK (auth.uid() = user_id);

-- ============================================
-- 2. Create user_exam_collections table
-- ============================================
CREATE TABLE IF NOT EXISTS "public"."user_exam_collections" (
    "id" bigint NOT NULL,
    "user_id" uuid NOT NULL,
    "exam_id" integer NOT NULL,
    "added_at" timestamp with time zone DEFAULT now() NOT NULL,
    "completion_count" integer DEFAULT 0 NOT NULL,
    "best_score" integer,
    "best_time_seconds" integer,
    "last_attempted_at" timestamp with time zone
);

ALTER TABLE "public"."user_exam_collections" OWNER TO "postgres";

ALTER TABLE "public"."user_exam_collections" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_exam_collections_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Primary key
ALTER TABLE ONLY "public"."user_exam_collections"
    ADD CONSTRAINT "user_exam_collections_pkey" PRIMARY KEY ("id");

-- Unique constraint
ALTER TABLE ONLY "public"."user_exam_collections"
    ADD CONSTRAINT "user_exam_collections_user_exam_unique" UNIQUE ("user_id", "exam_id");

-- Foreign keys
ALTER TABLE ONLY "public"."user_exam_collections"
    ADD CONSTRAINT "user_exam_collections_user_id_fkey" 
    FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."user_exam_collections"
    ADD CONSTRAINT "user_exam_collections_exam_id_fkey" 
    FOREIGN KEY ("exam_id") REFERENCES "public"."exams"("id") ON DELETE CASCADE;

-- Enable RLS
ALTER TABLE "public"."user_exam_collections" ENABLE ROW LEVEL SECURITY;

-- RLS Policy
CREATE POLICY "Users can manage their own exam collections" 
    ON "public"."user_exam_collections" 
    USING (auth.uid() = user_id) 
    WITH CHECK (auth.uid() = user_id);

-- ============================================
-- 3. Grant permissions
-- ============================================
GRANT ALL ON TABLE "public"."user_question_bank_collections" TO "anon";
GRANT ALL ON TABLE "public"."user_question_bank_collections" TO "authenticated";
GRANT ALL ON TABLE "public"."user_question_bank_collections" TO "service_role";

GRANT ALL ON SEQUENCE "public"."user_question_bank_collections_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."user_question_bank_collections_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_question_bank_collections_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."user_exam_collections" TO "anon";
GRANT ALL ON TABLE "public"."user_exam_collections" TO "authenticated";
GRANT ALL ON TABLE "public"."user_exam_collections" TO "service_role";

GRANT ALL ON SEQUENCE "public"."user_exam_collections_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."user_exam_collections_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_exam_collections_id_seq" TO "service_role";
