-- Enable RLS for new tables
-- Create distributions table
CREATE TABLE IF NOT EXISTS "public"."distributions" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "target_type" text NOT NULL CHECK (target_type IN ('question_bank', 'exam')),
  "target_id" bigint NOT NULL,
  "visibility" text NOT NULL DEFAULT 'public' CHECK (visibility IN ('public', 'assigned_only')),
  "note" text,
  "created_by" uuid REFERENCES "public"."profiles"("id"),
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "public"."distributions" ENABLE ROW LEVEL SECURITY;

-- Create distribution_users table
CREATE TABLE IF NOT EXISTS "public"."distribution_users" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "distribution_id" bigint NOT NULL REFERENCES "public"."distributions"("id") ON DELETE CASCADE,
  "user_id" uuid NOT NULL REFERENCES "public"."profiles"("id") ON DELETE CASCADE,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  UNIQUE("distribution_id", "user_id")
);

ALTER TABLE "public"."distribution_users" ENABLE ROW LEVEL SECURITY;

-- Create notifications table
CREATE TABLE IF NOT EXISTS "public"."notifications" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid NOT NULL REFERENCES "public"."profiles"("id") ON DELETE CASCADE,
  "type" text NOT NULL,
  "title" text NOT NULL,
  "message" text,
  "link" text,
  "is_read" boolean DEFAULT false,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "public"."notifications" ENABLE ROW LEVEL SECURITY;

-- Add visibility column to question_banks and exams
ALTER TABLE "public"."question_banks" 
ADD COLUMN IF NOT EXISTS "visibility" text DEFAULT 'public' CHECK (visibility IN ('public', 'assigned_only'));

ALTER TABLE "public"."exams" 
ADD COLUMN IF NOT EXISTS "visibility" text DEFAULT 'public' CHECK (visibility IN ('public', 'assigned_only'));

-- RLS Policies

-- distributions: Admins can do everything, users can view if they are part of it (implicitly handled by distribution_users query usually, but let's be safe)
-- Actually, distributions table is mainly for admin use. Users don't need to query it directly usually, they query distribution_users or the target tables.
-- But let's allow admins to manage distributions.

CREATE POLICY "Admins can manage distributions" ON "public"."distributions"
FOR ALL
USING (
  EXISTS (
    SELECT 1 FROM "public"."profiles"
    WHERE "profiles"."id" = auth.uid() AND "profiles"."is_admin" = true
  )
);

-- distribution_users: Admins can manage. Users can view their own.
CREATE POLICY "Admins can manage distribution_users" ON "public"."distribution_users"
FOR ALL
USING (
  EXISTS (
    SELECT 1 FROM "public"."profiles"
    WHERE "profiles"."id" = auth.uid() AND "profiles"."is_admin" = true
  )
);

CREATE POLICY "Users can view their own distribution entries" ON "public"."distribution_users"
FOR SELECT
USING (auth.uid() = "user_id");

-- notifications: Users can view and update (mark read) their own notifications. Admins can create them (via server actions usually, but policies good).
CREATE POLICY "Users can view their own notifications" ON "public"."notifications"
FOR SELECT
USING (auth.uid() = "user_id");

CREATE POLICY "Users can update their own notifications" ON "public"."notifications"
FOR UPDATE
USING (auth.uid() = "user_id");

CREATE POLICY "Admins can insert notifications" ON "public"."notifications"
FOR INSERT
WITH CHECK (
  EXISTS (
    SELECT 1 FROM "public"."profiles"
    WHERE "profiles"."id" = auth.uid() AND "profiles"."is_admin" = true
  )
);

-- Update RLS for question_banks
-- Drop existing policy if it conflicts or we need to replace it. 
-- Existing policy: "Published banks are viewable by everyone" USING (is_published = true)
-- We need to change this to:
-- (is_published = true AND (visibility IS NULL OR visibility = 'public'))
-- OR
-- (is_published = true AND visibility = 'assigned_only' AND user is in distribution list)

DROP POLICY IF EXISTS "Published banks are viewable by everyone" ON "public"."question_banks";

CREATE POLICY "Banks viewable by eligible users" ON "public"."question_banks"
FOR SELECT
USING (
  ("is_published" = true AND ("visibility" IS NULL OR "visibility" = 'public'))
  OR
  (
    "is_published" = true 
    AND "visibility" = 'assigned_only' 
    AND EXISTS (
      SELECT 1 FROM "public"."distributions" d
      JOIN "public"."distribution_users" du ON du."distribution_id" = d."id"
      WHERE d."target_type" = 'question_bank'
        AND d."target_id" = "question_banks"."id"
        AND du."user_id" = auth.uid()
    )
  )
);

-- Update RLS for exams
-- Assuming there is a similar policy for exams.
-- I should check the existing policy name for exams first to be safe, but dropping if exists is okay.
-- Based on exploration, exams also have RLS.

DROP POLICY IF EXISTS "Published exams are viewable by everyone" ON "public"."exams";
-- In case the name is different, I'll add a safe drop or just create a new one that might overlap if not careful.
-- Let's assume standard naming or just create a new comprehensive one.
-- Actually, checking schema.sql for exact policy name would be better, but "Published exams..." is likely.
-- Let's try to be generic or just create a new one.
-- Wait, if I don't drop the old one, and it says "is_published=true", then it will still allow access even if visibility is assigned_only.
-- So I MUST drop the old policy.
-- I'll check schema.sql content from memory/previous turns.
-- schema.sql had: CREATE POLICY "Published banks are viewable by everyone" ...
-- It didn't explicitly show exams policy in the summary, but it likely exists.
-- I will blindly drop "Published exams are viewable by everyone" and "Anyone can view published exams" just in case.

DROP POLICY IF EXISTS "Published exams are viewable by everyone" ON "public"."exams";
DROP POLICY IF EXISTS "Anyone can view published exams" ON "public"."exams";

CREATE POLICY "Exams viewable by eligible users" ON "public"."exams"
FOR SELECT
USING (
  ("is_published" = true AND ("visibility" IS NULL OR "visibility" = 'public'))
  OR
  (
    "is_published" = true 
    AND "visibility" = 'assigned_only' 
    AND EXISTS (
      SELECT 1 FROM "public"."distributions" d
      JOIN "public"."distribution_users" du ON du."distribution_id" = d."id"
      WHERE d."target_type" = 'exam'
        AND d."target_id" = "exams"."id"
        AND du."user_id" = auth.uid()
    )
  )
);

-- Index for performance
CREATE INDEX IF NOT EXISTS "idx_distributions_target" ON "public"."distributions" ("target_type", "target_id");
CREATE INDEX IF NOT EXISTS "idx_distribution_users_user" ON "public"."distribution_users" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_distribution_users_dist" ON "public"."distribution_users" ("distribution_id");
CREATE INDEX IF NOT EXISTS "idx_notifications_user_read" ON "public"."notifications" ("user_id", "is_read");
