-- Migration: Add exam unlock fields and user_exam_unlocks table
-- This mirrors question bank unlock mechanics for mock exams

ALTER TABLE "public"."exams"
ADD COLUMN IF NOT EXISTS "is_premium" boolean DEFAULT false NOT NULL;

ALTER TABLE "public"."exams"
ADD COLUMN IF NOT EXISTS "unlock_type" text DEFAULT 'free' NOT NULL;

ALTER TABLE "public"."exams"
ADD COLUMN IF NOT EXISTS "price" numeric;

CREATE TABLE IF NOT EXISTS "public"."user_exam_unlocks" (
    "id" bigint NOT NULL,
    "user_id" uuid NOT NULL,
    "exam_id" integer NOT NULL,
    "unlock_type" text NOT NULL,
    "referral_id" bigint,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "public"."user_exam_unlocks" OWNER TO "postgres";

ALTER TABLE "public"."user_exam_unlocks" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_exam_unlocks_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."user_exam_unlocks"
    ADD CONSTRAINT "user_exam_unlocks_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."user_exam_unlocks"
    ADD CONSTRAINT "user_exam_unlocks_user_exam_unique" UNIQUE ("user_id", "exam_id");

ALTER TABLE ONLY "public"."user_exam_unlocks"
    ADD CONSTRAINT "user_exam_unlocks_user_id_fkey"
    FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."user_exam_unlocks"
    ADD CONSTRAINT "user_exam_unlocks_exam_id_fkey"
    FOREIGN KEY ("exam_id") REFERENCES "public"."exams"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."user_exam_unlocks"
    ADD CONSTRAINT "user_exam_unlocks_referral_id_fkey"
    FOREIGN KEY ("referral_id") REFERENCES "public"."referrals"("id") ON DELETE SET NULL;

ALTER TABLE "public"."user_exam_unlocks" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own exam unlocks"
    ON "public"."user_exam_unlocks"
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

GRANT ALL ON TABLE "public"."user_exam_unlocks" TO "anon";
GRANT ALL ON TABLE "public"."user_exam_unlocks" TO "authenticated";
GRANT ALL ON TABLE "public"."user_exam_unlocks" TO "service_role";

GRANT ALL ON SEQUENCE "public"."user_exam_unlocks_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."user_exam_unlocks_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_exam_unlocks_id_seq" TO "service_role";
