-- Create question_banks table
CREATE TABLE IF NOT EXISTS public.question_banks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid uuid DEFAULT gen_random_uuid() NOT NULL,
    title text NOT NULL,
    description text,
    subject_id bigint NOT NULL REFERENCES public.subjects(id) ON DELETE CASCADE,
    is_premium boolean DEFAULT false NOT NULL,
    is_published boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create question_bank_items table
CREATE TABLE IF NOT EXISTS public.question_bank_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_id bigint NOT NULL REFERENCES public.question_banks(id) ON DELETE CASCADE,
    question_id bigint NOT NULL REFERENCES public.questions(id) ON DELETE CASCADE,
    order_index integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_question_banks_subject_id ON public.question_banks(subject_id);
CREATE INDEX IF NOT EXISTS idx_question_bank_items_bank_id ON public.question_bank_items(bank_id);
CREATE INDEX IF NOT EXISTS idx_question_bank_items_question_id ON public.question_bank_items(question_id);

-- Enable Row Level Security
ALTER TABLE public.question_banks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.question_bank_items ENABLE ROW LEVEL SECURITY;

-- Note: Adjust policies based on your specific auth requirements.
-- Below are permissive start policies.

-- Policy: Published banks are viewable by everyone (or just authenticated users)
CREATE POLICY "Published banks are viewable by everyone" 
ON public.question_banks FOR SELECT 
USING (is_published = true);

-- Policy: Admin/Creator can see all banks (Assuming authenticated users for now)
CREATE POLICY "Authenticated users can select all banks" 
ON public.question_banks FOR SELECT 
TO authenticated 
USING (true);

-- Policy: Admin can insert/update/delete (Assuming all authenticated users are admins for simplicity based on current setup, restrict this later!)
CREATE POLICY "Authenticated users can insert banks" 
ON public.question_banks FOR INSERT 
TO authenticated 
WITH CHECK (true);

CREATE POLICY "Authenticated users can update banks" 
ON public.question_banks FOR UPDATE 
TO authenticated 
USING (true);

CREATE POLICY "Authenticated users can delete banks" 
ON public.question_banks FOR DELETE 
TO authenticated 
USING (true);

-- Policies for Items
CREATE POLICY "Items are viewable if bank is published" 
ON public.question_bank_items FOR SELECT 
USING (
    EXISTS (
        SELECT 1 FROM public.question_banks 
        WHERE question_banks.id = question_bank_items.bank_id 
        AND question_banks.is_published = true
    )
);

CREATE POLICY "Authenticated users can manage items" 
ON public.question_bank_items FOR ALL 
TO authenticated 
USING (true);
