create table if not exists "public"."subject_exam_dates" (
    "id" bigint generated by default as identity primary key,
    "subject_id" integer references "public"."subjects"("id") on delete cascade not null,
    "exam_type" text not null check (exam_type in ('midterm', 'final')),
    "exam_date" timestamp with time zone not null,
    "created_at" timestamp with time zone default now() not null,
    unique ("subject_id", "exam_type")
);

alter table "public"."subject_exam_dates" enable row level security;

create policy "Anyone can view subject exam dates"
    on "public"."subject_exam_dates"
    for select
    using (true);

create policy "Admins can manage subject exam dates"
    on "public"."subject_exam_dates"
    for all
    to authenticated
    using (true)
    with check (true);

grant all on table "public"."subject_exam_dates" to authenticated;
grant select on table "public"."subject_exam_dates" to anon;
grant all on table "public"."subject_exam_dates" to service_role;
